.travis/install_osx.sh, .travis/run_osx.sh, install_deps.sh
=> Fix MacOSX builds

README.rst, docs/index.rst, docs/technical.rst
=> technical documentation extracted

pytrip/lib/filter_point.c, setup.py, tests/test_base.py, tests/test_dos.py, tests/test_let.py
=> WIP porting C extension to Python3

pytrip/cube.py, tests/requirements-test.txt
=> lstrip and rstrip replaced by more portable methods

.travis.yml, pytrip/__init__.py, pytrip/ctx.py, pytrip/dicomhelper.py, pytrip/dos.py, pytrip/field.py, pytrip/get_dvh.py, pytrip/guiutil.py, pytrip/let.py, pytrip/paths.py, pytrip/tripexecuter/tripexecuter.py, pytrip/utils/bevlet2letoerdat.py, pytrip/utils/bevlet2oer.py, pytrip/utils/gd2agr.py, pytrip/utils/gd2dat.py, pytrip/utils/rst_read.py, pytrip/vdx.py, setup.py
checking missing libraries disabled in specific places by # NOQA flake8 comment
Fixes #18
=> pep8 enabled

LICENSE, tests/test_let.py
skip travis build - [ci skip]
Fixes #50
=> libdedx removed

.travis.yml
=> Fix pip upload issue

.travis.yml, install_deps.sh, tox.ini
=> Fix packaging and docs targets in tox

setup.py
=> License fixed

pytrip/utils/slicedos.py, setup.py
Resolves #36 
This can be extended and improved indefinitly, for now I just wanted something which works.
=> Add script for making PNGs from CTX and DOS cubes.

pytrip/cube.py, pytrip/dicomhelper.py
pytrip was not loading properly .dcm files when using python 3.x
=> replaced obsolete sorting by cmp with sorting by key

pytrip/tripexecuter/voicollection.py
=> Fixed wrong import

.travis.yml, pytrip/utils/cubeslice.py, tests/test_converters.py
This will close #76 
Also, basicConfig() is not a part of the logger class, but a part of the logging module.
=> Add -o option to specify output directory

.travis.yml, .travis/install_osx.sh, README.rst, pytrip/utils/gd2dat.py, pytrip/vdx.py, tests/test_vdx.py
=> Improved vdx handling

pytrip/dos.py, pytrip/field.py, pytrip/let.py, pytrip/paths.py, pytrip/tripexecuter/tripexecuter.py, tests/test_dos.py, tests/test_let.py
=> pytriplib imports improved

.travis/install_linux.sh
=> versioneer for python 3.2 removed

.travis.yml
=> part of travis targets removed

pytrip/tripexecuter/tripexecuter.py, pytrip/tripexecuter/tripplan.py
=> Add dedx and hlut paths to plan class. Add docstrings.

.travis.yml, tox.ini
=> Travis update

pytrip/dos.py, tests/test_dos.py
=> dvh support improved

README.rst, pytrip/__init__.py, pytrip/tripexecuter/__init__.py, pytrip/tripexecuter/tripexecuter.py, tests/test_vdx.py
=> improve imports

pytrip/let.py
=> Add all docstrings to lvh.py

pytrip/cube.py
- added docstrings for cube.py #91 
- make two functions private which really are internal here
- a little bit of code cleanup
=> Add more docstrings

MANIFEST.in, examples/example01_vdx.py
=> vdx example code

pytrip/__init__.py, pytrip/utils/bevlet2letoerdat.py, pytrip/utils/bevlet2oer.py, pytrip/utils/cubeslice.py, pytrip/utils/dicom2trip.py, pytrip/utils/gd2agr.py, pytrip/utils/gd2dat.py, pytrip/utils/rst2sobp.py, pytrip/utils/rst_plot.py, pytrip/utils/rst_read.py, pytrip/utils/trip2dicom.py
=> Improved logging

pytrip/vdx.py
- related to #91 
- make a few functions private #131
=> Docstrings for VDX

pytrip/dos.py
=> Docstrings for DOS

pytrip/ctx.py
=> Docstrings for CTX

pytrip/file_parser.py, pytrip/raster.py
- Related to #91 
- Make some methods private #131
=> Docstrings for RST

README.rst, docs/examples.rst, docs/index.rst, examples/example00_basic.py
=> examples automatically included in RST files

README.rst, docs/getting_started.rst, docs/index.rst, docs/manipulating_cubes.rst, docs/user_guide.rst
=> new documentation layout

setup.py
=> Fixed invalid classifier

setup.py
=> Problematic classifier fixed

pytrip/__init__.py
=> missing dicomhelper import added

pytrip/utils/bevlet2oer.py, pytrip/utils/gd2agr.py, pytrip/utils/gd2dat.py, pytrip/utils/rst_plot.py, pytrip/vdx.py, tests/test_converters.py, tests/test_dos.py, tests/test_let.py, tests/test_vdx.py
=> reading .vdx file in 1.2 format

requirements.txt
=> restriction added for numpy 1.12

pytrip/utils/cubeslice.py
=> correct implementation of axis limits and image extent for CT data

pytrip/ctx.py, pytrip/cube.py, pytrip/dos.py, pytrip/utils/trip2dicom.py, pytrip/vdx.py
=> Saving DICOM from .vdx files which can be loaded into Eclipse

.travis.yml, .travis/install_linux.sh
=> Restricted setuptools version for py3.2 travis build

pytrip/utils/cubeslice.py, tests/test_converters.py
=> Fix bad slice numbering

pytrip/utils/cubeslice.py
Tested with TST001 from neptun.phys.au.dk/TRiP
Closes #199
=> Fix #199, dosecubes not being recognized.

pytrip/cube.py
=> Improve the meta data when creating empty cubes.

.travis.yml
=> Include python 3.6 in testing suite

pytrip/__init__.py, pytrip/ctx.py, pytrip/cube.py, pytrip/dos.py, pytrip/let.py, tests/test_ctx.py, tests/test_dos.py, tests/test_let.py
Fixes #66 
added different header files extension for various classes
LETCube will get .dosemlet.hed extension, other classes will get .hed extension
This will solve inambiguity in resolving class from filename
=> Custom header files extensions

pytrip/utils/cubeslice.py
now properly using filename parsing
improve debugging in #198
fixes #212
=> Improved reading of LET and DOS cubes in cubeslicer

.travis.yml, MANIFEST.in, setup.py
=> Removing tests from wheel package

pytrip/res/point.py, pytrip/vdx.py
=> Support handling bogus pinnacle dicom tags.

pytrip/dicomhelper.py
=> Add support for ".IMA" dicom file extension

examples/example01_vdx.py, examples/example02_trip98.py, pytrip/tripexecuter/tripexecuter.py, pytrip/utils/dicom2trip.py, pytrip/utils/trip2dicom.py, pytrip/vdx.py, tests/test_vdx.py
=> Unused content parameter removed

.travis.yml, wercker.yml
=> python3.6 added to manylinux1 target

pytrip/ctx.py, pytrip/cube.py
=> Fix #237, raystation not loading pytrip generated dicom files.

pytrip/vdx.py
Closes #243 https://github.com/pytrip/pytripgui/issues/60
=> Fix missing ROI names #243

pytrip/vdx.py
=> make rtss filename consitent closes #247

pytrip/tripexecuter/tripexecuter.py, pytrip/vdx.py, tests/test_paths.py
=> Fix api change, #252

pytrip/ctx.py, pytrip/cube.py, pytrip/dos.py, pytrip/vdx.py
=> missing tags added

.gitattributes, pytrip/cube.py, pytrip/dos.py, pytrip/vdx.py
=> Suggested fix for #254, bad patient_ids

pytrip/vdx.py
=> Possible fix for 1.2 VDX pixel size issue

pytrip/vdx.py, tests/test_vdx.py
Closes #269.
Needed by https://github.com/pytrip/pytripgui/pull/75
=> Fix slicing handling

pytrip/vdx.py
=> remove forbidden 'other' string from RT ROI Interpreted Type

pytrip/vdx.py
Closes #263
Will remove "in progress" once @TokePrintz confirms it works.
=> Fix CtxCube not being passed to VDX when dealing with 1.2 legacy vdx

pytrip/vdx.py, tests/test_vdx.py
=> Propose this hack to speedup trip2dicom conversion.

pytrip/cube.py, pytrip/dos.py
=> Fix missing PatientID when converting to trip->dicom #266

pytrip/utils/dicom2trip.py, pytrip/utils/trip2dicom.py
=> better catch of errors for dicom2trip

pytrip/ctx.py, pytrip/cube.py, pytrip/vdx.py
Fixes https://github.com/pytrip/pytripgui/issues/58 together with https://github.com/pytrip/pytripgui/pull/79
=> fix RTSS import issue

pytrip/tripexecuter/fieldcollection.py, pytrip/tripexecuter/tripexecuter.py, pytrip/tripexecuter/tripplancollection.py, pytrip/tripexecuter/voicollection.py
=> porting iterators to python3

pytrip/tripexecuter/tripexecuter.py
=> starting local process of TRiP98 which is both python 2 and 3 compatible

pytrip/tripexecuter/tripexecuter.py
=> prefix uuid for tripexe dir #287

pytrip/cube.py
=> make .hed more TRiP friendly

pytrip/vdx.py
=> fix TRiP bad offsets from dicom2trip

pytrip/ctx.py, pytrip/cube.py, pytrip/dos.py, pytrip/vdx.py
=> unique study instance UID

pytrip/cube.py
=> cube division operator ported to python3

pytrip/utils/cubeslice.py
=> max colorscale option

pytrip/tripexecuter/field.py, pytrip/tripexecuter/tripvoi.py, pytrip/tripexecuter/voi.py
=> typo fixed (toogle -> toggle)

appveyor.yml, requirements.txt
=> scipy version bumped

pytrip/__init__.py, pytrip/cube.py, pytrip/models/aux.py, pytrip/models/proton.py, pytrip/models/rcr.py, pytrip/models/tcp.py, tests/test_models.py
Closes #311  (adding RCR)
Closes #315  (adds proton stuff such as Carabe)
=> add biology models

pytrip/models/extra.py, pytrip/models/rcr.py
=> Rename aux.py to prevent appveyor issue

appveyor.yml
Related to #323 
It will fix this issue once new release of pytrip is made
=> python3.6 added to appveyor

pytrip/ddd.py
=> replaced looping over dictionary with python3 compatible way

pytrip/cube.py, pytrip/vdx.py
issues
closes #342 
closes #340
=> Repair coronal and saggital contour extraction

pytrip/vdx.py, tests/test_vdx.py
included fix for countours consisting of one point
Fixes #350
=> fixed looping over slices when calculating center position

.travis.yml, pytrip/ddd.py, pytrip/paths.py, pytrip/res/interpolate.py, pytrip/utils/bevlet2oer.py, requirements.txt, setup.py, tests/requirements-test.txt, tests/test_interpolate.py
Fixes #325 
Partially solving #242
=> new interpolator for DDD and other purposes

tox.ini
=> parallel building of sphinx doc disabled

install_versioneer.sh
=> reset gitattributes

pytrip/models/__init__.py, pytrip/models/extra.py, pytrip/models/proton.py
=> Add LQ-model and fix bad proton models.

appveyor.yml, pytrip/models/tcp.py, pytrip/util.py, pytrip/utils/dvhplot.py, tests/test_converters.py, tests/test_dos.py, tests/test_plot.py
closes #360 
closes #37 
closes #38
=> Add a generic volume_histogram function.

pytrip/__init__.py, pytrip/dicomhelper.py, pytrip/utils/dicom2trip.py, pytrip/utils/trip2dicom.py, tests/test_paths.py
=> Rename folder to dir, since API is changed anyway at 2.0 transition

pytrip/tripexecuter/execute.py, pytrip/tripexecuter/field.py, pytrip/tripexecuter/plan.py
=> Add some docstrings

tox.ini
=> sphinx version advanced

pytrip/models/proton.py, tests/test_models.py
=> Fix RBE issue #370

pytrip/tripexecuter/execute.py, tests/test_exec.py
=> typo fixed

pytrip/ctx.py, pytrip/cube.py, pytrip/models/extra.py, pytrip/models/proton.py, pytrip/models/rcr.py, pytrip/tripexecuter/execparser.py, pytrip/util.py
=> adjust for new flake8 #388

pytrip/tripexecuter/plan.py
=> rework plan dicts

pytrip/vdx.py
=> make vdx 2.0 parser more tolerant to newlines, and minimal check

examples/example00_basic.py, pytrip/cube.py, pytrip/dos.py, pytrip/paths.py, pytrip/tripexecuter/execute.py, pytrip/vdx.py, tests/test_let.py, tests/test_models.py
=> several pep8 issues fixed, detected by new version of flake8

.travis/install_linux.sh
=> limit py version as starting from 1.5 support for python 3.3 is dropped

.travis.yml, tests/requirements-test.txt
=> replacing abandonded pytest-capturelog

.travis.yml, .travis/deploy_package.sh, .travis/install_osx.sh, appveyor.yml, setup.py, tox.ini
=> dropping support for python 3.3

.travis/build_wheels.sh, requirements.txt, setup.py, tox.ini, wercker.yml
=> Fixed issue with numpy RC package deps

pytrip/ctx.py, pytrip/cube.py, pytrip/dicomhelper.py, pytrip/dos.py, pytrip/raster.py, pytrip/vdx.py, requirements.txt, setup.py, tests/requirements-test.txt
which require new way of importing
=> support for newer (>1.0) version of pydicom package

pytrip/ctx.py, pytrip/cube.py, pytrip/dos.py, pytrip/utils/dicom2trip.py, pytrip/vdx.py, wercker.yml
=> update for new pydicom tags

pytrip/util.py, pytrip/utils/dvhplot.py, pytrip/volhist.py, setup.cfg, tests/test_dos.py
=> Add new VolHist class to pytrip.

pytrip/cube.py
=> Fix for reading 8-byte float cubes #436.

pytrip/dos.py, pytrip/let.py, pytrip/volhist.py, tests/test_dos.py
- add write method to VolHist
- add deprecation warnings to old DVH method
- add logger to let.py
=> VolHist related updates

pytrip/spc.py
=> fixed wrong SPC normalization code

appveyor.yml, pytrip/spc.py, pytrip/utils/spc2pdf.py, setup.py, tests/test_converters.py
=> spc2pdf implementation

.travis.yml, appveyor.yml
=> Adjusting to pip 10.0x

pytrip/let.py, pytrip/volhist.py
=> Fix volhist issues

pytrip/vdx.py
=> Suggested fix for #461.

pytrip/tripexecuter/plan.py
=> Fix missing iterations command, #459

pytrip/cube.py
=> Possible fix for #460, missing z-tables.

examples/example01_vdx.py, pytrip/cube.py, pytrip/dos.py, pytrip/let.py, pytrip/lib/filter_point.c, pytrip/res/point.py, pytrip/utils/dvhplot.py, pytrip/vdx.py, tests/requirements-test.txt, tests/test_exec.py, tests/test_vdx.py
=> Multi-contour per VOI

pytrip/cube.py, pytrip/vdx.py
=> set basename upon dicom CT and RTSS import

pytrip/vdx.py
=> VDX writer: Avoid repeating single points in a slice 

.travis/build_wheels.sh, .travis/install_linux.sh, tests/requirements-test.txt
=> old tox for python3.2

pytrip/cube.py
=> setting writable option on arrays generated with frombuffer method 

pytrip/paths.py, pytrip/tripexecuter/execute.py, pytrip/tripexecuter/field.py, pytrip/tripexecuter/plan.py, pytrip/vdx.py
=> various PEP8 fixes

pytrip/utils/spc2pdf.py
=> Loop over A added in SPC2PDF converter

pytrip/ctx.py
=> Previous comments were incomplete

.travis.yml, .travis/build_wheels.sh, appveyor.yml, appveyor/deploy_package.sh, requirements.txt
=> improved appveyor config

pytrip/tripexecuter/execparser.py, pytrip/tripexecuter/plan.py
=> parse_exec should be part of public API

.travis.yml
=> python version upgrade

appveyor.yml
=> missing python 3.7 and 3.8 added

pytrip/dos.py, pytrip/field.py, pytrip/let.py, pytrip/paths.py, pytrip/vdx.py, setup.py, tests/test_dos.py, tox.ini
=> improved packaging

.travis.yml, pytrip/spc.py, pytrip/tripexecuter/execute.py, pytrip/tripexecuter/plan.py, requirements.txt, setup.py, tox.ini, wercker.yml
=> Special numpy version for python 3.5

setup.py
=> better dependency specification for numpy

.travis.yml, appveyor.yml, pytrip/tripexecuter/field.py, pytrip/tripexecuter/plan.py, wercker.yml
=> saving bev file

pytrip/tripexecuter/plan.py
=> bev generation command moved after optimisation part

pytrip/tripexecuter/execute.py
This change is needed by gui to properly display progress
https://github.com/pytrip/pytripgui/issues/292
=> Sending stdout while trip98 is working

pytrip/tripexecuter/execute.py
=> extracting a tarball is doing on a local machine

pytrip/cube.py, pytrip/vdx.py
=> Trip accepts files with only '\n' as new line

pytrip/tripexecuter/execute.py
Remove code duplication
Connection with private key (un)protected works
Connection with username/password works
related to:
https://github.com/pytrip/pytripgui/pull/357
=> Execute trip remotely

pytrip/vdx.py
=> VOI colors

pytrip/lib/core.c, pytrip/vdx.py
=> documenting code

.gitignore
=> gitignore for jetbrains

.github/dependabot.yml, .github/workflows/main.yml
=> full tests for dependabot

README.rst, pytrip/concave_tool.py, pytrip/res/concave_tool.py, pytrip/vdx.py
=> add concave contours support

pytrip/dos.py, pytrip/vdx.py
All tags were also verified as up to date with DICOM 2021e (current version).
=> Hotfix for deprecated dicom tags in dos.py

pytrip/lib/core.c, pytrip/vdx.py
how it was:
```External
sagittal time: 17.839640617370605 s
coronal time: 12.245706558227539 s
External elapsed: 30.128231048583984
CTV_6000
sagittal time: 0.4264366626739502 s
coronal time: 0.5313541889190674 s
CTV_6000 elapsed: 0.9587903022766113
BrainStem
sagittal time: 0.14860320091247559 s
coronal time: 0.1306602954864502 s
BrainStem elapsed: 0.2802610397338867
Chiasm
sagittal time: 0.027945995330810547 s
coronal time: 0.016968965530395508 s
Chiasm elapsed: 0.044914960861206055
LacrimalGland_L
sagittal time: 0.015944957733154297 s
coronal time: 0.02394270896911621 s
LacrimalGland_L elapsed: 0.03988766670227051
LacrimalGland_R
sagittal time: 0.01400899887084961 s
coronal time: 0.020938634872436523 s
LacrimalGland_R elapsed: 0.03494763374328613
Lens_L
sagittal time: …
```
=> speed up intersections
